import Footer from "@/component/Footer/Footer";
import NavBar from "@/component/NavBar/NavBar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Hadeer 1st Next Pro",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: {
    default: "Hadeer 1st Next Pro",
    template: "%s | Hadeer 1st Next Pro",
  },

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
